service: sendSMSservice

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1

functions:
  commonService:
    handler: index.common_service
    timeout: 30
    events:
      - http:
          path: /api/v1/commonService
          method: post
          cors: true     
      - sqs:
          arn: arn:aws:sqs:us-east-1:319126977349:smsQueue
          batchSize: 10
          maximumBatchingWindow: 60  
                    
plugins:
  - serverless-offline          

